blog/urls.py
__author__ = 'sj_gao'
from django.conf.urls import patterns, url
import views

urlpatterns = patterns("",
                       url(r"^$", views.blog_list, name="blog_list"),
                       url(r"^article$", views.blog_list),
                       url(r'^detail/$', views.blog_detail, name="blog_detail"),
                       url(r'^about/$', views.blog_about, name="blog_about"),
                       )

codelife/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # url(r'^$', 'codelife.views.home', name='home'),
    url(r'^$', 'blog.views.blog_list', name='home'),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^wechat/', include('wechat.urls')),
)

blog/models.py
#encoding=utf-8
from django.db import models
from DjangoUeditor.models import UEditorField


# Create your models here.
class Tag(models.Model):
    tag_name = models.CharField(max_length=20)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.tag_name


class Classification(models.Model):
    name = models.CharField(max_length=20)

    def __unicode__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    website = models.URLField(blank=True)

    def __unicode__(self):
        return u'%s' % (self.name)


class Article(models.Model):
    caption = models.CharField(max_length=30)
    subcaption = models.CharField(max_length=50, blank=True)
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author)
    classification = models.ForeignKey(Classification)
    tags = models.ManyToManyField(Tag, blank=True)
    content = UEditorField(u'内容   ',width=600, height=600, toolbars="full", imagePath="images/",
                           filePath="docs/",
                           upload_settings={"imageMaxSize":1204000},
                           settings={},command=None,blank=True)
    publish_or_not = models.BooleanField("是否要发表？", default=False)


class Resume(models.Model):
    name = models.CharField("resume name", max_length=30)
    content = UEditorField(u'内容   ',width=600, height=600, toolbars="full", imagePath="images/",
                           filePath="docs/",
                           upload_settings={"imageMaxSize":1204000},
                           settings={},command=None,blank=True)
    show_or_not = models.BooleanField("是否要发表？", default=False)
    last_update = models.DateTimeField(auto_now_add=True)

wechat/models.py
# -*- coding: utf8 -*-

from django.db import models
from DjangoUeditor.models import UEditorField
import json
# Create your models here.


class Tag(models.Model):
    tag_name = models.CharField(max_length=20)
    create_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.tag_name


class ImageText(models.Model):
    title = models.CharField("标题", max_length=40, unique=True )
    description = models.CharField("描述", max_length=120, blank=True)
    picurl = models.URLField("图片链接", blank=True)
    url = models.URLField("图文跳转链接")
    tags = models.ManyToManyField(Tag, blank=True)
    content = UEditorField(u'内容   ', width=600, height=600, toolbars="full", imagePath="images/",
                           filePath="docs/",
                           upload_settings={"imageMaxSize": 1204000},
                           settings={}, command=None, blank=True)

    origin_url = models.URLField("原文链接", blank=True)


class Response(models.Model):
    """
        存储回应内容，回复内容前，先在这里查找是否有对应的内容，没有的话，再新生成一个
    """
    keyword = models.CharField(max_length=80)
    content = models.TextField()
    md5_value = models.CharField(max_length=100)
    last_update = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.keyword


class Message(models.Model):
    context = models.CharField(max_length=100)
    add_time = models.DateTimeField(auto_now_add=True)


class LinuxCmd(models.Model):
    name = models.CharField("命令名称", max_length=20, unique=True )
    tags = models.ManyToManyField(Tag, blank=True)
    brief = models.TextField("命令简介", max_length=600)
    content = UEditorField(u'内容   ', width=600, height=600, toolbars="full", imagePath="images/",
                           filePath="docs/",
                           upload_settings={"imageMaxSize": 1204000},
                           settings={}, command=None, blank=True)

    url = models.URLField("参考资源", blank=True)

TYPE = (
    ("str", "string"),
    ("int", "int"),
    ("int", "boolean"),
    ("float", "float"),
    ("json", "json")
)


class SettingManager(models.Manager):

    def get_value_by_key(self, key):
        try:
            model = self.model.objects.get(key=key)
            if model.type == "json":
                return json.loads(model.value)
            return eval(model.type)(model.value)
        except self.model.DoesNotExist:
            return None
        except UnicodeEncodeError:
            return model.value

    def set_value_by_key(self, key, value, key_type=None):
        if key_type is None:
            if isinstance(value, dict) or isinstance(value, list):
                key_type = "json"
                value = json.dumps(value)
            else:
                key_type = type(value).__name__
        try:
            model = self.model.objects.get(key=key)
            model.value = value
            model.type = key_type
            model.save()
        except self.model.DoesNotExist:
            self.model(key=key, value=value, type=key_type).save()
        return True


class Setting(models.Model):
    key = models.CharField(max_length=255, unique=True)
    value = models.TextField(null=True, blank=True)
    type = models.CharField(choices=TYPE, help_text="key类型", max_length=50)
    is_enabled = models.BooleanField(default=True, help_text="是否启用该配置")
    is_scheduled = models.BooleanField(default=True,blank=True, help_text="是否启用计划时间， 不启用则默认永久有效")
    start_time = models.DateTimeField(verbose_name="配置生效开始时间", blank=True, null=True)
    end_time = models.DateTimeField(verbose_name="配置生效结束时间", blank=True, null=True)
    brief = models.TextField(help_text="帮助说明", blank=True)
    add_time = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    objects = SettingManager()

    def __unicode__(self):
        return "%s" % self.key

blog/views.py
# coding=utf8
from django.shortcuts import render
from blog.models import Article, Tag, Classification, Resume
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import Http404
from datetime import datetime
# Create your views here.
try:
    from ipdb import set_trace
except:
    pass


def blog_list(request):
    archive_date = request.GET.get("archive_date", None)
    classified = request.GET.get("classified", None)
    date_list = []
    cls_list = []
    for article in Article.objects.order_by("-publish_time"):        
        ar_datetime =  article.publish_time        
        date_list.append("%s-%s" % (ar_datetime.year, ar_datetime.month))
        cls_list.append(article.classification.name)        
    if archive_date:
        year = archive_date.split("-")[0]
        month = archive_date.split("-")[1]
        blogs = Article.objects.filter(publish_or_not=1, publish_time__year=year, publish_time__month=month).order_by('-publish_time')
    elif classified:
        blogs = Article.objects.filter(publish_or_not=1, classification__name=classified).order_by('-publish_time')
    else:
        blogs = Article.objects.filter(publish_or_not=1).order_by('-publish_time')
    return render_to_response('index.html', {"blogs": blogs, "date_set": set(date_list), "cls_set": set(cls_list)}, context_instance=RequestContext(request))


def blog_detail(request):
    if request.method == 'GET':
        id = request.GET.get('id', '')
        try:
            blog = Article.objects.get(id=id)
        except Article.DoesNotExist:
            raise Http404
        return render_to_response("detail.html", {"blog": blog}, context_instance=RequestContext(request))
    else:
        raise Http404


def blog_about(request):
    try:
        about_me = Resume.objects.filter(show_or_not=1)[0].content
    except:
        about_me = ""
    return render_to_response('about.html', {"about_me": about_me}, context_instance=RequestContext(request))

blog/templates/about.html
{% extends "base.html" %}
{% block extrajs %}
<script type="text/javascript">
    $(function(){
        $("nav.blog-nav a:eq(0)").removeClass("active");
        $("nav.blog-nav a:eq(5)").addClass("active");
    });
</script>
{% endblock %}
{% block title %}About Me{% endblock %}
{% block content_body %}
<div class="blog-about">
    <div class="intro">
        <h1 class="page-title">关于我</h1>
        {{about_me|safe}}

<!--         <p class="message">
            大家好，我叫Kevinstoic，是一名程序员。
        </p>

        <h3>我的经历</h3>

        <ul>
            <li>2008-2012 西北农林科技大学机电学院 </li>
            <li>2012-2014 复旦大学微电子系 </li>
            <li>2014-至今 在一家互联网公司做运维开发。</li>
        </ul>

        <h3>我的技能</h3>

        <ul>
            <li>编程语言：C, Python。钟爱Python</li>
            <li>网站开发：略懂前端，会写css+js，会使用bootstrap， jquery，比较喜欢后端，通常使用Django框架，本博客也是用Django搭建的。</li>
            <li>移动开发：做过移动开发的小项目，用Sencha Touch做的</li>
            <li>IT技能： 平时做项目要接触的知识比较广泛，对Linux，Mysql，Celery，RabbitMQ,Kafka, Docker略懂一二</li>
        </ul>

        <h3>生活中的我</h3>

        <ul>
            <li>喜欢折腾各种新技术，喜欢乔帮主的那句名言Stay Hungry， Stay Foolish</li>
            <li>喜欢各种球类运动，篮球，足球，乒乓，羽毛球，台球，不过水平比较渣</li>
            <li>喜欢看电影和电视剧，有段时间比较狂热，经常熬夜追剧</li>
            <li>喜欢思考，喜欢尝试各种新鲜事物</li>
            <li>喜欢阅读，心理学，历史，政治，文学都有所涉猎</li>
        </ul>

        <h3>Contact</h3>

        &nbsp&nbsp<p>联系方式：kevinstoic@126.com</p>

        &nbsp&nbsp<p>微信公众号：linux-world</p> -->

    </div>

</div>

{% endblock %}

blog/templates/base.html

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="../../static/css/common/bootstrap.min.css">
    <link rel="stylesheet" href="/static/blog/css/blog.css">
    {% block extracss %} {% endblock %}
    <script type="text/javascript" src="../../static/js/common/jquery-1.10.0.min.js"></script>
    <script type="text/javascript" src="../../static/js/common/bootstrap.min.js"></script>
    {% block extrajs %} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="blog-masthead">
        <div class="container">
            <nav class="blog-nav">
                <!--<a href="/blog/"><img src="../static/blog/images/logo.jpg" alt="LOGO" name="logo" width="180" height="60" id="logo" /></a>-->
                <a href="/blog" class="blog-nav-item active" >首页</a>
                <!--<a href="/rss/" class="blog-nav-item">订阅</a>-->
                <a href="#" class="blog-nav-item " onclick="alert('this column will be online in future!')">Python online docs</a>
                <a href="#" class="blog-nav-item " onclick="alert('this column will be online in future!')">Books Recommand</a>
                <a href="#" class="blog-nav-item " onclick="alert('this column will be online in future!')">Multimedia</a>
                <a href="#" class="blog-nav-item " onclick="alert('this column will be online in future!')">Developer Websites Navi</a>
                <a href="/blog/about/" class="blog-nav-item">关于</a>
            </nav>
        </div>
    </div>

    <div class="content_body">
        {% block content_body %}{% endblock %}
    </div>

    <div class="blog-footer">
        <div id="footer_logo"></div>
        <div id="siteinfo">&copy; 2014 - 2015 Codelife Blog Powered by hackstoic</div>
        <p>
            <a href="#">Back to top</a>
        </p>
    </div><!-- end .footer -->

</body>
</html>

blog/templates/detail.html
{% extends "base.html" %}
{% block title %} {{ blog.caption }} - Codelife {% endblock %}

{% load comments %}

{% block content_body %}
<div class="main-body">
    <div class="blog_body">
        <div class="blog-post-title">{{ blog.caption }}</div>
        <div class="blog-info1">
          <span class="blog-info1-list">
          <span class="li_small_1">分类：<a href="/blog/article?classified={{blog.classification}}">{{ blog.classification }}</a></span>
          <span class="li_small_1">作者：<a href="#">{{ blog.author }}</a></span>
          <span class="li_small_1">发表时间：{{ blog.publish_time|date:"Y-m-d H:i" }}</span>
        </span>
        </div>
        <div class="blog-splitline"></div>
        <div class="blog-post-content">{{ blog.content | safe }}</div>
    </div>


<!--     <div class="comments">
        <a name="blog_comments" id="comments"></a>
        {% get_comment_count for blog as comment_count %}
        <div class="comments_nav">评论({{ comment_count }})</div>
        {% ifequal comment_count 0 %}
        <div class="comments_body">
            <div class="comment_container">没有评论
            </div>
            {% else %}
            {% get_comment_list for blog as comments %}
            <div class="comments_body">
                {% for comment in comments %}
                <div class="comment_container">
                    <div class="comment_id"><a href="{{ comment.user_url }}"><img src="/static/images/hp.jpg" width="42" height="42" /></a></div>
                    <div class="cmt_user_info">
                        <span class="li_small_2">{{ comment.user_name }}</span>
                        <span class="li_small_2">{{ comment.submit_date|date:"Y-m-d H:i"}}</span>
                        <span class="reply_comment" id="{{ comment.user_name }}"><a href="#newcomment">回复</a></span>
                    </div>
                    <div id="comment_content">{{ comment.comment }}</div>
                </div>
                {% endfor %}
                {% endifequal %}
            </div>

            <div class="comments_nav">新的评论</div>
            {% get_comment_form for blog as blog_form %}
            <div class="comments_body">
                <div class="comment_form">
                    <form class="form-horizontal" action="{% comment_form_target %}" method="post" id="cmt_sub_form">
                        {% csrf_token %}
                        {{ blog_form.object_pk }}
                        {{ blog_form.content_type }}
                        {{ blog_form.timestamp }}
                        {{ blog_form.site }}
                        {{ blog_form.submit_date }}
                        {{ blog_form.security_hash }}
                        <div class="control-group">
                            <label class="control-label" for="id_name">用户名： </label>
                            <div class="controls">
                                <input type="text" id="id_name" class="input-xlarge" name="name" placeholder="请输入您的用户名" value="{{ user.username }}"/>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="id_email">E-mail： </label>
                            <div class="controls">
                                <input class="input-xlarge" id="id_email" type="email" name="email" placeholder="请输入您的邮箱地址" value="{{ user.email }}"/>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="id_email">网址： </label>
                            <div class="controls">
                                <input class="input-xlarge" id="id_url" type="url" name="url" placeholder="请输入您的网址" value="{{ user.url }}"/>
                            </div>
                        </div>
                        <a name="newcomment" id="newcomment"></a>
                        <div class="control-group">
                            <label class="control-label" for="id_comment">评论： </label>
                            <div class="controls">
                                <textarea class="input-xlarge comment" id="id_comment" name="comment" placeholder="请输入评论内容"></textarea>
                            </div>
                        </div>
                        <p style="display:none;"><label for="id_honeypot">如果你在该字段中输入任何内容，你的评论就会被视为垃圾评论。</label> <input type="text" name="honeypot" id="id_honeypot"></p>
                        <div class="controls">
                            <div class="form-actions">
                                <input class="btn btn-info" id="submit_btn" type="submit" name="submit" value="提交"/>
                                <input type="hidden" name="next" value="/detail/?id={{ blog.id }}"/>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div> -->
  {% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% load chinese_cut %}

{% block title %}Codelife{% endblock %}

{% block content_body %}
<div class="container">
    <div class="blog-header">
        <h1 class="blog-title">The CodeLife Blog</h1>
        <p class="lead blog-description">记录和分享编程生涯的点点滴滴</p>
    </div>
    <div class="row">
        <div class="col-sm-8 blog-main">
            {% for blog in blogs %}
            <div class="blog-post">
                <div class="blog-post-title"><a href="/blog/detail/?id={{ blog.id }}">{{ blog.caption }}</a></div>
                <!-- <div class="blog_title"><a href="/blog/#">{{ blog.caption }}</a></div> -->
                <div class="blog-info1">
            <span class="blog-info1-list">
              <span class="li_small_1">分类：<a href="/blog/article?classified={{blog.classification}}">{{ blog.classification }}</a></span>
              <span class="li_small_1">发表时间：{{ blog.publish_time|date:"Y-m-d H:i" }}</span>
            </span>
                </div>
                <div class="blog-splitline"></div>
                <div class="blog-description">{{ blog.content|striptags|chinese_cut:":100"|safe}}</div>
                <div class="blog-info2">
            <span class="blog-info2-list">
              <span class="li_small_2">标签：{% for tag in blog.tags.all %}<a href="#">{{ tag.tag_name }}&nbsp &nbsp</a>{% endfor %}</span>
            </span>
                </div>
            </div>
           {% endfor %}

        </div> <!-- /.blog-main -->
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">
                <h4>About Blog</h4>
                <p>Hello I'm <em>hackstoic</em>，I'd like to share technology knowledge and viewpoint in this blog. 分享技术相关的内容，以及对技术和生活的一些拙见。</p>
            </div>
            <div class="sidebar-module">
                <h4>Classified</h4>
                <ol class="list-unstyled">
                    {% for cls in cls_set %}
                    <li><a href="/blog/article?classified={{cls}}">{{cls}}</a></li>
                    {% endfor %}
                </ol>
            </div>
            <div class="sidebar-module">
                <h4>Archive</h4>
                <ol class="list-unstyled">
                    {% for ar_date in date_set %}
                    <li><a href="/blog/article?archive_date={{ar_date}}">{{ar_date}}</a></li>
                    {% endfor %}
                </ol>
            </div>
            <div class="sidebar-module">
                <h4>个人相关链接</h4>
                <ol class="list-unstyled">
                    <li><a href="http://weibo.com/u/5616283578" target="_blank">Weibo微博</a></li>
                    <li><a href="https://github.com/hackstoic" target="_blank">GitHub</a></li>
                    <li><a href="http://stackoverflow.com/users/4982426/hackstoic" target="_blank">Stackoverflow</a></li>
                    <li><a href="http://www.zhihu.com/people/hack-stoic" target="_blank">知乎</a></li>
                    <li><a href="http://blog.csdn.net/hackstoic" target="_blank">CSDN博客</a></li>
                    <!-- <li><a href="http://weixin.sogou.com/gzh?openid=oIWsFt8YwvO6eWtx7Q0M7FPdOyE0" target="_blank">微信公众号1</a></li> -->
                     <li><a href="http://weixin.sogou.com/gzh?openid=oIWsFt9_XkmM65rYnYNM1dFUSlLE" target="_blank">微信公众号</a></li>
                </ol>
            </div>
        </div><!-- /.blog-sidebar -->
    </div> <!-- /.row -->
</div><!-- /.container -->
{% endblock %}